# Generated by Django 5.2.5 on 2025-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
